#!/usr/bin/env Rscript

# GSE14520 stable-recoding and Firth Cox sensitivity analysis.
#
# Required input:
#   GSE14520_SOURCE_CSV: FigS17_GSE14520_four_gene_score_source_data.csv
#
# The source CSV should be generated by scripts/10_GSE14520_validation.R.
# This script retains binary AFP >300 ng/mL recoding and uses Firth-penalized
# Cox regression to assess whether the score association is robust to
# separation-prone clinicopathologic covariates.

options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
  library(coxphf)
  library(dplyr)
  library(tibble)
  library(readr)
  library(survival)
})

source_csv <- Sys.getenv(
  "GSE14520_SOURCE_CSV",
  unset = file.path(
    "results", "GSE14520_validation",
    "FigS17_GSE14520_four_gene_score_source_data.csv"
  )
)
outdir <- Sys.getenv(
  "GSE14520_FIRTH_OUTDIR",
  unset = file.path("results", "GSE14520_firth_cox_sensitivity")
)
dir.create(outdir, recursive = TRUE, showWarnings = FALSE)

if (!file.exists(source_csv)) stop("Missing GSE14520 source CSV: ", source_csv, call. = FALSE)

required <- c(
  "OS_time_months", "OS_status", "score_z", "AFP_group",
  "cirrhosis_group", "main_tumor_size_group", "multinodular_group"
)
dat <- read_csv(source_csv, show_col_types = FALSE)
missing <- setdiff(required, names(dat))
if (length(missing) > 0) stop("Missing columns: ", paste(missing, collapse = ", "), call. = FALSE)

mv_df <- dat %>%
  filter(if_all(all_of(required), ~ !is.na(.x))) %>%
  mutate(
    AFP_group = factor(AFP_group, levels = c("<=300", ">300")),
    cirrhosis_group = factor(cirrhosis_group, levels = c("No", "Yes")),
    main_tumor_size_group = factor(main_tumor_size_group, levels = c("Small", "Large")),
    multinodular_group = factor(multinodular_group, levels = c("No", "Yes"))
  )

formula <- Surv(OS_time_months, OS_status) ~
  AFP_group + cirrhosis_group + main_tumor_size_group + multinodular_group + score_z

standard_fit <- coxph(formula, data = mv_df, x = TRUE, y = TRUE)
standard_summary <- summary(standard_fit)
standard_terms <- as.data.frame(standard_summary$coefficients) %>%
  rownames_to_column("term") %>%
  left_join(
    as.data.frame(standard_summary$conf.int) %>% rownames_to_column("term"),
    by = "term"
  )

firth_fit <- coxphf(formula, data = mv_df)
firth_terms <- tibble(
  term = names(firth_fit$coefficients),
  coefficient = as.numeric(firth_fit$coefficients),
  hazard_ratio = exp(as.numeric(firth_fit$coefficients)),
  CI95_low = as.numeric(firth_fit$ci.lower),
  CI95_high = as.numeric(firth_fit$ci.upper),
  profile_likelihood_p = as.numeric(firth_fit$prob)
)

score_row <- firth_terms %>% filter(term == "score_z")
if (nrow(score_row) != 1) stop("Could not identify score_z in Firth Cox output.", call. = FALSE)

qc <- tibble(
  check = c(
    "complete_case_n",
    "events",
    "all_firth_confidence_intervals_finite",
    "score_hazard_ratio_positive",
    "score_direction_adverse"
  ),
  observed = c(
    nrow(mv_df),
    sum(mv_df$OS_status == 1),
    all(is.finite(firth_terms$CI95_low) & is.finite(firth_terms$CI95_high)),
    is.finite(score_row$hazard_ratio) && score_row$hazard_ratio > 0,
    is.finite(score_row$hazard_ratio) && score_row$hazard_ratio > 1
  ),
  expected = c(
    "Report observed value",
    "Report observed value",
    TRUE,
    TRUE,
    "Directionally adverse if supported"
  )
)

write_csv(standard_terms, file.path(outdir, "GSE14520_standard_cox_terms.csv"))
write_csv(firth_terms, file.path(outdir, "GSE14520_firth_cox_terms.csv"))
write_csv(qc, file.path(outdir, "GSE14520_firth_cox_QC.csv"))
message("GSE14520 Firth Cox outputs written to: ", outdir)
