# ===========================================================
# 11_spatial_transcriptomics.R
# Purpose: Spatial validation of glycolysis-immunosuppression
#          co-localization in HCC Visium samples (GSE238264)
# Corresponds to: Methods Section 2.14, Results Section 3.13
# ============================================================

library(Seurat)
library(ggplot2)
library(patchwork)

# ── Glycolysis gene set ────────────────────────────────────
glyco_genes <- c("HK1","HK2","GPI","PFKL","PFKP","PFKM","ALDOA","ALDOB","ALDOC",
                 "TPI1","GAPDH","PGK1","PGAM1","ENO1","ENO2","PKM","LDHA","LDHB",
                 "SLC2A1","SLC2A3","PFKFB3","GCK")

# ── Sample IDs ────────────────────────────────────────────
sample_ids <- c("HCC1R","HCC2R","HCC3R","HCC4R")

# NOTE: Download GSE238264 data from GEO and set path below
# Each sample folder should contain: barcodes.tsv.gz, features.tsv.gz,
# matrix.mtx.gz, tissue_positions.csv, scalefactors_json.json,
# tissue_hires_image.png
data_dir <- "D:/scRNA_project/GSE238264/"

results_list <- list()

for (sid in sample_ids) {
  cat("Processing sample:", sid, "\n")
  sample_path <- file.path(data_dir, sid)

  # Load Visium data
  seu_st <- Load10X_Spatial(data.dir = sample_path, slice = sid)

  # QC filter
  seu_st <- subset(seu_st,
                   nFeature_Spatial >= 200 &
                   PercentageFeatureSet(seu_st, pattern = "^MT-") < 25)
  cat("  Spots after QC:", ncol(seu_st), "\n")

  # Normalize
  seu_st <- SCTransform(seu_st, assay = "Spatial", verbose = FALSE)

  # Glycolysis module score
  avail_genes <- glyco_genes[glyco_genes %in% rownames(seu_st)]
  seu_st <- AddModuleScore(
    seu_st,
    features = list(avail_genes),
    name     = "Glycolysis_Score",
    ctrl     = 100
  )

  # Stratify spots
  med_score <- median(seu_st$Glycolysis_Score1)
  seu_st$glyco_group <- ifelse(seu_st$Glycolysis_Score1 >= med_score,
                                "GlycoHigh", "GlycoLow")

  # Differential expression of ENO1, SPP1, MIF
  target_genes <- c("ENO1","SPP1","MIF")
  avail_targets <- target_genes[target_genes %in% rownames(seu_st)]

  expr_mat  <- GetAssayData(seu_st, assay = "SCT", layer = "data")
  high_cells <- colnames(seu_st)[seu_st$glyco_group == "GlycoHigh"]
  low_cells  <- colnames(seu_st)[seu_st$glyco_group == "GlycoLow"]

  de_results <- sapply(avail_targets, function(g) {
    wt <- wilcox.test(
      expr_mat[g, high_cells],
      expr_mat[g, low_cells],
      alternative = "greater"
    )
    fc <- mean(expr_mat[g, high_cells]) - mean(expr_mat[g, low_cells])
    c(p_value = wt$p.value, log2FC = fc)
  })

  results_list[[sid]] <- as.data.frame(t(de_results))
  results_list[[sid]]$gene   <- rownames(results_list[[sid]])
  results_list[[sid]]$sample <- sid

  cat("  DE results:\n"); print(results_list[[sid]])

    # Spatial feature plots (candidate Figure 9A; final Figure 9 layout is assembled separately)
  p1 <- SpatialFeaturePlot(seu_st, features = "ENO1") + ggtitle(paste(sid, "ENO1"))
  p2 <- SpatialFeaturePlot(seu_st, features = "Glycolysis_Score1") +
    ggtitle(paste(sid, "Glycolysis Score"))
  p3 <- SpatialFeaturePlot(seu_st, features = "SPP1") + ggtitle(paste(sid, "SPP1"))
  p4 <- SpatialFeaturePlot(seu_st, features = "MIF")  + ggtitle(paste(sid, "MIF"))

  p_combined <- (p1 | p2) / (p3 | p4)
  ggsave(paste0("D:/scRNA_project/Fig9A_spatial_", sid, ".png"),
         p_combined, width = 10, height = 8, dpi = 300)
}

# ── Legacy exploratory spatial DE bubble plot; not a final numbered figure ──────────────
# Final Figure 9B direction-consistency panel is regenerated by:
# revision_figure_restore/plot_Fig9B_spatial_direction_consistency.R
all_results <- do.call(rbind, results_list)
all_results$neg_log_p <- -log10(all_results$p_value)
all_results$sig <- ifelse(all_results$p_value < 0.05,
                           ifelse(all_results$p_value < 0.001, "***",
                                  ifelse(all_results$p_value < 0.01, "**", "*")),
                           "ns")

p_bubble <- ggplot(all_results,
                   aes(x = sample, y = gene,
                       size = neg_log_p, color = log2FC)) +
  geom_point() +
  geom_text(aes(label = sig), vjust = -1.2, size = 3.5) +
  scale_size_continuous(name = "-log10(p)", range = c(2, 12)) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red",
                        midpoint = 0, name = "log2FC") +
  labs(x = NULL, y = NULL,
       title = "Spatial Validation: Glycolysis-High vs Low Spots",
       subtitle = "GlycoHigh vs GlycoLow | 4 HCC Visium samples") +
  theme_classic(base_size = 13) +
  theme(axis.text = element_text(size = 12))

ggsave("D:/scRNA_project/legacy_spatial_DE_bubble_summary.png",
       p_bubble, width = 8, height = 5, dpi = 300)
ggsave("D:/scRNA_project/legacy_spatial_DE_bubble_summary.pdf",
       p_bubble, width = 8, height = 5)

# Save results table
write.csv(all_results, "D:/scRNA_project/spatial_DE_results.csv", row.names = FALSE)
cat("Spatial transcriptomics analysis complete.\n")
# ── Supplementary Figure S18: Spatial GlycoHigh/GlycoLow stratification ──────
library(Seurat)
library(ggplot2)
library(patchwork)

sample_ids  <- c("HCC1R", "HCC2R", "HCC3R", "HCC4R")
sample_dirs <- paste0("D:/scRNA_project/GSE238264/", sample_ids, "/", sample_ids)

glyco_genes <- c(
  "HK1","HK2","GPI","PFKL","PFKP","PFKM","ALDOA","ALDOB","ALDOC",
  "TPI1","GAPDH","PGK1","PGAM1","ENO1","ENO2","PKM","LDHA","LDHB",
  "SLC2A1","SLC2A3","PFKFB3","GCK"
)

plot_list <- list()
for (i in seq_along(sample_ids)) {
  sid <- sample_ids[i]
  seu <- Load10X_Spatial(sample_dirs[i])
  seu <- NormalizeData(seu, assay = "Spatial", verbose = FALSE)
  glyco_present <- intersect(glyco_genes, rownames(seu))
  seu <- AddModuleScore(seu, features = list(glyco_present),
                        name = "Glycolysis", assay = "Spatial")
  med_score      <- median(seu$Glycolysis1)
  seu$GlycoGroup <- factor(
    ifelse(seu$Glycolysis1 >= med_score, "GlycoHigh", "GlycoLow"),
    levels = c("GlycoLow", "GlycoHigh")
  )
  n_high <- sum(seu$GlycoGroup == "GlycoHigh")
  n_low  <- sum(seu$GlycoGroup == "GlycoLow")
  cat(sid, "— High:", n_high, "/ Low:", n_low, "\n")
  p <- SpatialDimPlot(
    seu, group.by = "GlycoGroup",
    cols = c("GlycoHigh" = "#D73027", "GlycoLow" = "#4575B4"),
    pt.size.factor = 1.4, alpha = c(0.8, 0.8)
  ) +
    ggtitle(sprintf("%s  (GlycoHigh = %d / GlycoLow = %d)", sid, n_high, n_low)) +
    theme(plot.title = element_text(size = 11, face = "bold", hjust = 0.5))
  plot_list[[i]] <- p
}

combined_s18 <- wrap_plots(plot_list, ncol = 2) +
  plot_annotation(
    title    = "Spatial GlycoHigh / GlycoLow spot stratification",
    subtitle = "Spots stratified by median Glycolysis1 score within each sample",
    theme = theme(plot.title    = element_text(size = 13, face = "bold", hjust = 0.5),
                  plot.subtitle = element_text(size = 10, hjust = 0.5))
  )
ggsave("D:/scRNA_project/FigS18_spatial_GlycoGroup.png",
       combined_s18, width = 12, height = 10, dpi = 300)
ggsave("D:/scRNA_project/FigS18_spatial_GlycoGroup.pdf",
       combined_s18, width = 12, height = 10)
cat("FigS18 saved.\n")
# ============================================================
# Final submission figure restoration note
# ============================================================
# Spatial transcriptomics results are part of the final Figure 9
# spatial analysis, not Figure 8.
#
# Candidate per-sample spatial feature plots generated here are
# named Fig9A_spatial_<sample>.png.
#
# The final clean vector version of the spatial GlycoHigh versus
# GlycoLow direction-consistency panel is regenerated in:
# revision_figure_restore/plot_Fig9B_spatial_direction_consistency.R
#
# The final clean vector version of the RCTD-estimated spatial
# cell-type composition panel is Supplementary Figure S20 and is
# regenerated in:
# revision_figure_restore/plot_FigS20_RCTD_celltype_composition.R
#
# Spatial results should be described as spot-level tissue
# co-enrichment, not as causal cell-cell communication or clinical
# prediction.
