#!/usr/bin/env Rscript

# ============================================================
# 17_partial_correlation_metabolic_specificity.R
#
# Supplementary Figure S21:
# Metabolic pathway specificity of SPP1 and MIF ligand expression
# in tumor-derived hepatocytes.
#
# Final manuscript-locked purpose:
#   Compute partial Spearman correlations between ligand expression
#   and glycolysis or OXPHOS activity in tumor-derived hepatocytes.
#
# Locked inputs:
#   input object: seurat_final.rds
#   patient_col  = "patient"
#   celltype_col = "cell_type"
#   site_col     = "site"
#   gly_col      = "Glycolysis_AUC"
#
# Locked selection:
#   tumor-derived hepatocytes:
#     site == "Tumor" & cell_type == "Hepatocyte"
#   expected n = 15,391
#
# Locked method:
#   OXPHOS_AUC is read from the S21 source generated by
#   14_OXPHOS_metabolic_specificity.R if available.
#   If that source file is absent, OXPHOS_AUC is computed here
#   using the same 39-gene OXPHOS set and AUCell parameters.
#
#   Partial Spearman correlations are computed using ppcor::pcor.test:
#     SPP1 ~ Glycolysis_AUC | OXPHOS_AUC
#     SPP1 ~ OXPHOS_AUC    | Glycolysis_AUC
#     MIF  ~ Glycolysis_AUC | OXPHOS_AUC
#     MIF  ~ OXPHOS_AUC    | Glycolysis_AUC
#
# Locked manuscript checkpoints:
#   Glycolysis-OXPHOS Spearman rho approximately 0.066
#   SPP1 glycolysis partial rho approximately 0.227
#   SPP1 OXPHOS partial rho approximately 0.125
#   MIF  glycolysis partial rho approximately 0.105
#   MIF  OXPHOS partial rho approximately 0.242
#
# Mandatory output order:
#   1. Source CSV files
#   2. QC CSV file
#   3. PDF/PNG only if QC PASS
#
# Figure note:
#   No "Supplementary Figure S21" title is printed inside the figure.
# ============================================================

options(stringsAsFactors = FALSE)

# ----------------------------
# Package handling
# ----------------------------
required_packages <- c(
  "Seurat",
  "SeuratObject",
  "AUCell",
  "dplyr",
  "tidyr",
  "readr",
  "tibble",
  "stringr",
  "ggplot2",
  "ppcor"
)

load_or_stop <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop(
      "Package '", pkg, "' is required but not installed.\n",
      "Install CRAN packages with install.packages().\n",
      "Install Bioconductor packages with BiocManager::install().",
      call. = FALSE
    )
  }
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}

invisible(lapply(required_packages, load_or_stop))

# Avoid masking in interactive sessions.
select       <- dplyr::select
mutate       <- dplyr::mutate
filter       <- dplyr::filter
arrange      <- dplyr::arrange
summarise    <- dplyr::summarise
group_by     <- dplyr::group_by
ungroup      <- dplyr::ungroup
left_join    <- dplyr::left_join
rename       <- dplyr::rename
count        <- dplyr::count
bind_rows    <- dplyr::bind_rows
n_distinct   <- dplyr::n_distinct
all_of       <- dplyr::all_of

# ----------------------------
# User paths
# ----------------------------
# Recommended:
#   Place seurat_final.rds in the working directory.
# Optional:
#   Sys.setenv(SEURAT_FINAL_RDS = "/path/to/seurat_final.rds")
rds_path <- Sys.getenv("SEURAT_FINAL_RDS", unset = "seurat_final.rds")

outdir <- file.path("results", "FigS21_metabolic_specificity")
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

# Source file generated by 14_OXPHOS_metabolic_specificity.R.
oxphos_source_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_cell_source.csv")

# ----------------------------
# Locked columns and expected values
# ----------------------------
patient_col  <- "patient"
celltype_col <- "cell_type"
site_col     <- "site"
gly_col      <- "Glycolysis_AUC"

expected_n_tumor_hep <- 15391L
expected_median_cut <- 0.2203849
expected_low_n <- 7696L
expected_high_n <- 7695L

median_tolerance <- 1e-6
rho_tolerance <- 0.035

expected_results <- tibble::tribble(
  ~ligand, ~metabolic_program, ~adjusted_for,      ~expected_rho,
  "SPP1",  "Glycolysis",       "OXPHOS",            0.227,
  "SPP1",  "OXPHOS",           "Glycolysis",        0.125,
  "MIF",   "Glycolysis",       "OXPHOS",            0.105,
  "MIF",   "OXPHOS",           "Glycolysis",        0.242
)

expected_gly_ox_rho <- 0.066

# ----------------------------
# Gene sets
# ----------------------------
oxphos_genes_locked <- c(
  # Complex I
  "NDUFB3", "NDUFB4", "NDUFB5", "NDUFB6", "NDUFB7",
  "NDUFB8", "NDUFB9", "NDUFB10", "NDUFA1", "NDUFA2",
  "NDUFA3", "NDUFA4", "NDUFS1", "NDUFS2", "NDUFS3",
  # Complex II
  "SDHA", "SDHB", "SDHC", "SDHD",
  # Complex III
  "UQCRB", "UQCRC1", "UQCRC2", "UQCRQ", "CYC1",
  # Complex IV
  "COX4I1", "COX5A", "COX5B", "COX6A1", "COX6B1",
  "COX7A2", "COX8A",
  # Complex V
  "ATP5F1A", "ATP5F1B", "ATP5F1C", "ATP5F1D", "ATP5F1E",
  "ATP5MC1", "ATP5MC2", "ATP5MC3", "ATP5PB"
)

ligands <- c("SPP1", "MIF")

# ----------------------------
# Helper functions
# ----------------------------
qc_row <- function(check, observed, expected, pass, tolerance = NA_character_) {
  tibble::tibble(
    check = check,
    observed = as.character(observed),
    expected = as.character(expected),
    tolerance = as.character(tolerance),
    pass = as.logical(pass)
  )
}

get_counts_mat <- function(seu, assay) {
  tryCatch(
    {
      SeuratObject::LayerData(seu, assay = assay, layer = "counts")
    },
    error = function(e) {
      Seurat::GetAssayData(seu, assay = assay, slot = "counts")
    }
  )
}

get_norm_mat <- function(seu, assay) {
  tryCatch(
    {
      SeuratObject::LayerData(seu, assay = assay, layer = "data")
    },
    error = function(e) {
      Seurat::GetAssayData(seu, assay = assay, slot = "data")
    }
  )
}

format_p <- function(x) {
  ifelse(is.na(x), NA_character_,
         ifelse(x == 0, "<1e-300", sprintf("%.3e", x)))
}

partial_spearman_ppcor <- function(dat, ligand, metabolic_program, adjusted_for) {
  x <- dat[[ligand]]
  y <- dat[[metabolic_program]]
  z <- dat[[adjusted_for]]

  ok <- stats::complete.cases(x, y, z)
  x <- x[ok]
  y <- y[ok]
  z <- z[ok]

  if (length(x) < 10) {
    return(tibble::tibble(
      ligand = ligand,
      metabolic_program = metabolic_program,
      adjusted_for = adjusted_for,
      n_cells = length(x),
      partial_spearman_rho = NA_real_,
      p_value = NA_real_
    ))
  }

  ct <- ppcor::pcor.test(
    x = x,
    y = y,
    z = z,
    method = "spearman"
  )

  tibble::tibble(
    ligand = ligand,
    metabolic_program = metabolic_program,
    adjusted_for = adjusted_for,
    n_cells = length(x),
    partial_spearman_rho = as.numeric(ct$estimate),
    p_value = as.numeric(ct$p.value)
  )
}

compute_oxphos_auc <- function(counts_mat, cells_use, oxphos_genes) {
  oxphos_present <- intersect(oxphos_genes, rownames(counts_mat))
  oxphos_missing <- setdiff(oxphos_genes, oxphos_present)

  if (length(oxphos_present) < 4) {
    stop("Fewer than 4 OXPHOS genes are present; AUCell scoring is not meaningful.", call. = FALSE)
  }

  expr_counts <- counts_mat[, cells_use, drop = FALSE]
  auc_max_rank <- ceiling(0.05 * nrow(expr_counts))

  rankings <- AUCell::AUCell_buildRankings(
    exprMat = expr_counts,
    plotStats = FALSE,
    verbose = FALSE
  )

  cells_auc <- AUCell::AUCell_calcAUC(
    geneSets = list(OXPHOS = oxphos_present),
    rankings = rankings,
    aucMaxRank = auc_max_rank,
    verbose = FALSE
  )

  auc <- as.numeric(AUCell::getAUC(cells_auc)["OXPHOS", ])
  names(auc) <- colnames(AUCell::getAUC(cells_auc))

  list(
    auc = auc,
    oxphos_present = oxphos_present,
    oxphos_missing = oxphos_missing,
    auc_max_rank = auc_max_rank,
    source = "computed_in_17"
  )
}

# ----------------------------
# Load object and validate metadata
# ----------------------------
if (!file.exists(rds_path)) {
  stop(
    "Cannot find seurat_final.rds.\n",
    "Current rds_path = ", rds_path, "\n",
    "Place seurat_final.rds in the working directory or set SEURAT_FINAL_RDS.",
    call. = FALSE
  )
}

seu <- readRDS(rds_path)
meta <- seu@meta.data %>% tibble::rownames_to_column("cell")

required_cols <- c(patient_col, celltype_col, site_col, gly_col)
missing_cols <- setdiff(required_cols, colnames(meta))
if (length(missing_cols) > 0) {
  stop("Missing required metadata columns: ", paste(missing_cols, collapse = ", "), call. = FALSE)
}

assay_use <- if ("RNA" %in% names(seu@assays)) "RNA" else DefaultAssay(seu)
norm_mat <- get_norm_mat(seu, assay_use)

# ----------------------------
# Select tumor-derived hepatocytes
# ----------------------------
tumor_hep <- meta %>%
  dplyr::filter(
    .data[[site_col]] == "Tumor",
    .data[[celltype_col]] == "Hepatocyte"
  ) %>%
  dplyr::mutate(
    patient = .data[[patient_col]],
    Glycolysis_AUC = as.numeric(.data[[gly_col]])
  )

cat("Selected tumor-derived hepatocytes:", nrow(tumor_hep), "\n")

if (nrow(tumor_hep) != expected_n_tumor_hep) {
  cat("\nAvailable Tumor-site cell_type labels:\n")
  print(sort(table(meta[[celltype_col]][meta[[site_col]] == "Tumor"]), decreasing = TRUE))
  stop(
    "Selected tumor-derived hepatocytes != 15,391. ",
    "Do not continue until metadata labels and selection rules are corrected.",
    call. = FALSE
  )
}

if (anyNA(tumor_hep$Glycolysis_AUC)) {
  stop("Glycolysis_AUC contains NA values in selected tumor-derived hepatocytes.", call. = FALSE)
}

median_cut <- median(tumor_hep$Glycolysis_AUC, na.rm = TRUE)

tumor_hep <- tumor_hep %>%
  dplyr::mutate(
    gly_group = ifelse(Glycolysis_AUC > median_cut, "High", "Low"),
    gly_group = factor(gly_group, levels = c("Low", "High"))
  )

gly_table <- table(tumor_hep$gly_group)
low_n <- as.integer(gly_table[["Low"]])
high_n <- as.integer(gly_table[["High"]])

cat("Median Glycolysis_AUC cutoff:", median_cut, "\n")
cat("GlycoLow:", low_n, " | GlycoHigh:", high_n, "\n")

# ----------------------------
# Build analysis data
# ----------------------------
missing_ligands <- setdiff(ligands, rownames(norm_mat))
if (length(missing_ligands) > 0) {
  stop("Missing ligand genes in normalized expression matrix: ",
       paste(missing_ligands, collapse = ", "), call. = FALSE)
}

expr_ligand <- as.matrix(norm_mat[ligands, tumor_hep$cell, drop = FALSE])

dat <- tumor_hep %>%
  dplyr::select(
    cell,
    patient,
    Glycolysis_AUC,
    gly_group
  ) %>%
  dplyr::mutate(
    SPP1 = as.numeric(expr_ligand["SPP1", cell]),
    MIF = as.numeric(expr_ligand["MIF", cell])
  )

oxphos_source_mode <- NA_character_
oxphos_present <- character(0)
oxphos_missing <- character(0)
auc_max_rank <- NA_integer_

if (file.exists(oxphos_source_csv)) {
  cat("Reading OXPHOS_AUC from source generated by 14: ", oxphos_source_csv, "\n", sep = "")
  oxsrc <- readr::read_csv(oxphos_source_csv, show_col_types = FALSE)

  required_oxsrc_cols <- c("cell", "OXPHOS_AUC")
  missing_oxsrc_cols <- setdiff(required_oxsrc_cols, colnames(oxsrc))
  if (length(missing_oxsrc_cols) > 0) {
    stop("OXPHOS source CSV is missing columns: ",
         paste(missing_oxsrc_cols, collapse = ", "), call. = FALSE)
  }

  dat <- dat %>%
    dplyr::left_join(
      oxsrc %>%
        dplyr::select(cell, OXPHOS_AUC) %>%
        dplyr::mutate(OXPHOS_AUC = as.numeric(OXPHOS_AUC)),
      by = "cell"
    )

  oxphos_source_mode <- "read_from_14_source_csv"
  oxphos_present <- oxphos_genes_locked
  oxphos_missing <- character(0)
} else {
  cat("No OXPHOS source CSV from 14 detected. Computing OXPHOS_AUC inside 17.\n")
  counts_mat <- get_counts_mat(seu, assay_use)

  ox <- compute_oxphos_auc(
    counts_mat = counts_mat,
    cells_use = tumor_hep$cell,
    oxphos_genes = oxphos_genes_locked
  )

  dat <- dat %>%
    dplyr::mutate(
      OXPHOS_AUC = as.numeric(ox$auc[cell])
    )

  oxphos_source_mode <- ox$source
  oxphos_present <- ox$oxphos_present
  oxphos_missing <- ox$oxphos_missing
  auc_max_rank <- ox$auc_max_rank
}

if (anyNA(dat$OXPHOS_AUC)) {
  stop("OXPHOS_AUC contains NA values after source loading/computation.", call. = FALSE)
}

dat <- dat %>%
  dplyr::rename(
    Glycolysis = Glycolysis_AUC,
    OXPHOS = OXPHOS_AUC
  )

# ----------------------------
# Correlations and partial correlations
# ----------------------------
gly_ox_ct <- suppressWarnings(
  stats::cor.test(dat$Glycolysis, dat$OXPHOS, method = "spearman", exact = FALSE)
)

gly_ox_rho <- as.numeric(gly_ox_ct$estimate)
gly_ox_p <- as.numeric(gly_ox_ct$p.value)

partial_results <- dplyr::bind_rows(
  partial_spearman_ppcor(dat, "SPP1", "Glycolysis", "OXPHOS"),
  partial_spearman_ppcor(dat, "SPP1", "OXPHOS", "Glycolysis"),
  partial_spearman_ppcor(dat, "MIF", "Glycolysis", "OXPHOS"),
  partial_spearman_ppcor(dat, "MIF", "OXPHOS", "Glycolysis")
) %>%
  dplyr::mutate(
    FDR = stats::p.adjust(p_value, method = "BH"),
    comparison = paste0(metabolic_program, " adjusted for ", adjusted_for),
    ligand = factor(ligand, levels = c("SPP1", "MIF")),
    metabolic_program = factor(metabolic_program, levels = c("Glycolysis", "OXPHOS")),
    label = sprintf("%.3f", partial_spearman_rho),
    p_value_label = format_p(p_value),
    FDR_label = format_p(FDR)
  ) %>%
  dplyr::left_join(
    expected_results,
    by = c("ligand", "metabolic_program", "adjusted_for")
  ) %>%
  dplyr::mutate(
    rho_delta_from_expected = partial_spearman_rho - expected_rho,
    within_expected_tolerance = abs(rho_delta_from_expected) <= rho_tolerance
  ) %>%
  dplyr::arrange(ligand, metabolic_program)

print(partial_results)

summary_source <- tibble::tibble(
  metric = c(
    "n_cells",
    "n_patients",
    "glycolysis_oxphos_spearman_rho",
    "glycolysis_oxphos_spearman_p",
    "oxphos_source_mode",
    "oxphos_genes_present",
    "oxphos_genes_missing",
    "auc_max_rank_if_computed_in_17"
  ),
  value = c(
    as.character(nrow(dat)),
    as.character(dplyr::n_distinct(dat$patient)),
    sprintf("%.6f", gly_ox_rho),
    format_p(gly_ox_p),
    oxphos_source_mode,
    paste(oxphos_present, collapse = ";"),
    ifelse(length(oxphos_missing) == 0, "None", paste(oxphos_missing, collapse = ";")),
    as.character(auc_max_rank)
  )
)

gene_set_source <- tibble::tibble(
  gene = oxphos_genes_locked,
  gene_set = "OXPHOS_39_core_ETC_subunits",
  present_for_AUCell = oxphos_genes_locked %in% oxphos_present,
  missing_for_AUCell = oxphos_genes_locked %in% oxphos_missing
)

manifest <- tibble::tibble(
  item = c(
    "script",
    "figure",
    "input_object",
    "assay_used",
    "selection_rule",
    "selected_tumor_hepatocytes",
    "glycolysis_variable",
    "OXPHOS_variable",
    "ligand_expression_layer",
    "partial_correlation_method",
    "multiple_testing",
    "plot_title_policy",
    "spatial_or_same_cell_claim"
  ),
  value = c(
    "17_partial_correlation_metabolic_specificity.R",
    "Supplementary Figure S21",
    rds_path,
    assay_use,
    "site == 'Tumor' & cell_type == 'Hepatocyte'",
    as.character(nrow(dat)),
    "Glycolysis_AUC",
    "OXPHOS_AUC",
    "Seurat RNA data layer / normalized log-expression",
    "ppcor::pcor.test(method = 'spearman')",
    "Benjamini-Hochberg FDR across four partial-correlation tests",
    "No 'Supplementary Figure S21' title is printed inside the figure",
    "This is single-cell expression association within selected tumor-derived hepatocytes, not a causal or direct signaling assay."
  )
)

# ----------------------------
# Write source CSVs before QC/figures
# ----------------------------
cell_source_csv <- file.path(outdir, "FigS21_partial_correlation_input_cells.csv")
result_source_csv <- file.path(outdir, "FigS21_partial_correlation_metabolic_specificity_source.csv")
summary_source_csv <- file.path(outdir, "FigS21_partial_correlation_summary_source.csv")
gene_set_csv <- file.path(outdir, "FigS21_partial_correlation_OXPHOS_gene_set_source.csv")
manifest_csv <- file.path(outdir, "FigS21_partial_correlation_manifest.csv")

readr::write_csv(dat, cell_source_csv)
readr::write_csv(partial_results, result_source_csv)
readr::write_csv(summary_source, summary_source_csv)
readr::write_csv(gene_set_source, gene_set_csv)
readr::write_csv(manifest, manifest_csv)

cat("\nSource CSVs written:\n")
cat("  ", cell_source_csv, "\n", sep = "")
cat("  ", result_source_csv, "\n", sep = "")
cat("  ", summary_source_csv, "\n", sep = "")
cat("  ", gene_set_csv, "\n", sep = "")
cat("  ", manifest_csv, "\n", sep = "")

# ----------------------------
# Mandatory QC
# ----------------------------
checkpoint_text <- partial_results %>%
  dplyr::mutate(
    text = paste0(
      as.character(ligand), " ",
      as.character(metabolic_program), "|", adjusted_for,
      "=",
      sprintf("%.3f", partial_spearman_rho),
      " expected ",
      sprintf("%.3f", expected_rho)
    )
  ) %>%
  dplyr::pull(text) %>%
  paste(collapse = "; ")

qc <- dplyr::bind_rows(
  qc_row(
    "Input object exists",
    file.exists(rds_path),
    TRUE,
    file.exists(rds_path)
  ),
  qc_row(
    "Required metadata columns",
    paste(required_cols, collapse = ";"),
    paste(required_cols, collapse = ";"),
    length(missing_cols) == 0
  ),
  qc_row(
    "Selected tumor-derived hepatocytes",
    nrow(dat),
    expected_n_tumor_hep,
    nrow(dat) == expected_n_tumor_hep
  ),
  qc_row(
    "Median Glycolysis_AUC cutoff",
    sprintf("%.7f", median_cut),
    sprintf("%.7f", expected_median_cut),
    abs(median_cut - expected_median_cut) <= median_tolerance,
    median_tolerance
  ),
  qc_row(
    "GlycoLow count",
    low_n,
    expected_low_n,
    low_n == expected_low_n
  ),
  qc_row(
    "GlycoHigh count",
    high_n,
    expected_high_n,
    high_n == expected_high_n
  ),
  qc_row(
    "Ligand genes present",
    paste(ligands, collapse = ";"),
    "SPP1;MIF",
    length(missing_ligands) == 0
  ),
  qc_row(
    "OXPHOS_AUC source",
    oxphos_source_mode,
    "read_from_14_source_csv or computed_in_17",
    oxphos_source_mode %in% c("read_from_14_source_csv", "computed_in_17")
  ),
  qc_row(
    "OXPHOS_AUC finite values",
    all(is.finite(dat$OXPHOS)),
    TRUE,
    all(is.finite(dat$OXPHOS))
  ),
  qc_row(
    "Glycolysis-OXPHOS Spearman rho",
    sprintf("%.6f", gly_ox_rho),
    sprintf("%.3f", expected_gly_ox_rho),
    abs(gly_ox_rho - expected_gly_ox_rho) <= rho_tolerance,
    rho_tolerance
  ),
  qc_row(
    "Glycolysis-OXPHOS Spearman p",
    format_p(gly_ox_p),
    "approximately 2.44e-12; p < 1e-6 required",
    is.finite(gly_ox_p) && gly_ox_p < 1e-6
  ),
  qc_row(
    "Partial Spearman checkpoint rho values",
    checkpoint_text,
    paste0("All within +/-", rho_tolerance, " of locked manuscript values"),
    all(partial_results$within_expected_tolerance, na.rm = FALSE),
    rho_tolerance
  ),
  qc_row(
    "SPP1 glycolysis partial exceeds SPP1 OXPHOS partial",
    sprintf(
      "%.3f > %.3f",
      partial_results$partial_spearman_rho[
        partial_results$ligand == "SPP1" &
          partial_results$metabolic_program == "Glycolysis"
      ],
      partial_results$partial_spearman_rho[
        partial_results$ligand == "SPP1" &
          partial_results$metabolic_program == "OXPHOS"
      ]
    ),
    "TRUE",
    partial_results$partial_spearman_rho[
      partial_results$ligand == "SPP1" &
        partial_results$metabolic_program == "Glycolysis"
    ] >
      partial_results$partial_spearman_rho[
        partial_results$ligand == "SPP1" &
          partial_results$metabolic_program == "OXPHOS"
      ]
  ),
  qc_row(
    "MIF OXPHOS partial exceeds MIF glycolysis partial",
    sprintf(
      "%.3f > %.3f",
      partial_results$partial_spearman_rho[
        partial_results$ligand == "MIF" &
          partial_results$metabolic_program == "OXPHOS"
      ],
      partial_results$partial_spearman_rho[
        partial_results$ligand == "MIF" &
          partial_results$metabolic_program == "Glycolysis"
      ]
    ),
    "TRUE",
    partial_results$partial_spearman_rho[
      partial_results$ligand == "MIF" &
        partial_results$metabolic_program == "OXPHOS"
    ] >
      partial_results$partial_spearman_rho[
        partial_results$ligand == "MIF" &
          partial_results$metabolic_program == "Glycolysis"
      ]
  ),
  qc_row(
    "All four partial-correlation FDR values significant",
    paste(format_p(partial_results$FDR), collapse = ";"),
    "All FDR < 0.05",
    all(partial_results$FDR < 0.05, na.rm = TRUE)
  ),
  qc_row(
    "Figure has no manuscript-number title",
    "No ggtitle/labs(title) used",
    "No 'Supplementary Figure S21' title inside figure",
    TRUE
  )
)

qc_status <- ifelse(all(qc$pass), "PASS", "FAIL")
qc <- qc %>% dplyr::mutate(overall_qc = qc_status)

qc_csv <- file.path(outdir, "FigS21_partial_correlation_QC_check.csv")
readr::write_csv(qc, qc_csv)

cat("\nQC CSV written:\n")
cat("  ", qc_csv, "\n", sep = "")
cat("\nQC table:\n")
print(qc)

if (!all(qc$pass)) {
  stop(
    "Mandatory QC failed. Source CSV and QC CSV were written, but PDF/PNG figures were not generated.\n",
    "Inspect: ", qc_csv,
    call. = FALSE
  )
}

# ----------------------------
# Plot only after QC PASS
# ----------------------------
plot_df <- partial_results %>%
  dplyr::mutate(
    ligand = factor(as.character(ligand), levels = c("SPP1", "MIF")),
    metabolic_program = factor(
      as.character(metabolic_program),
      levels = c("Glycolysis", "OXPHOS")
    )
  )

fig <- ggplot2::ggplot(
  plot_df,
  ggplot2::aes(x = ligand, y = partial_spearman_rho, fill = metabolic_program)
) +
  ggplot2::geom_hline(yintercept = 0, linewidth = 0.35) +
  ggplot2::geom_col(
    position = ggplot2::position_dodge(width = 0.72),
    width = 0.62,
    color = "black",
    linewidth = 0.25
  ) +
  ggplot2::geom_text(
    ggplot2::aes(label = label),
    position = ggplot2::position_dodge(width = 0.72),
    vjust = -0.45,
    size = 3.8
  ) +
  ggplot2::coord_cartesian(ylim = c(0, 0.30)) +
  ggplot2::labs(
    x = NULL,
    y = "Partial Spearman rho",
    fill = NULL
  ) +
  ggplot2::theme_classic(base_size = 12) +
  ggplot2::theme(
    axis.text = ggplot2::element_text(color = "black"),
    axis.title = ggplot2::element_text(color = "black"),
    legend.position = "bottom",
    plot.margin = ggplot2::margin(8, 10, 8, 8)
  )

pdf_file <- file.path(outdir, "FigS21_partial_correlation_metabolic_specificity.pdf")
png_file <- file.path(outdir, "FigS21_partial_correlation_metabolic_specificity.png")

ggplot2::ggsave(pdf_file, fig, width = 5.4, height = 4.2, useDingbats = FALSE)
ggplot2::ggsave(png_file, fig, width = 5.4, height = 4.2, dpi = 600)

cat("\nQC PASS. Figure files written:\n")
cat("  ", pdf_file, "\n", sep = "")
cat("  ", png_file, "\n", sep = "")

cat("\nSupplementary Figure S21 partial-correlation metabolic-specificity analysis complete.\n")
