#!/usr/bin/env Rscript

# ============================================================
# 14_OXPHOS_metabolic_specificity.R
#
# OXPHOS AUCell scoring and metabolic-specificity input QC.
#
# Current role in the repository:
#   This script prepares the OXPHOS_AUC source data used by the
#   Supplementary Figure S21 metabolic-specificity analysis.
#
# Important figure-mapping correction:
#   This script does NOT generate Supplementary Figure S22.
#   Supplementary Figure S22 is the NicheNet ligand activity analysis.
#   Partial-correlation plotting for Supplementary Figure S21 is handled
#   by 17_partial_correlation_metabolic_specificity.R.
#
# Locked inputs:
#   input object: seurat_final.rds
#   patient_col  = "patient"
#   celltype_col = "cell_type"
#   site_col     = "site"
#   gly_col      = "Glycolysis_AUC"
#
# Locked selection:
#   tumor-derived hepatocytes:
#     site == "Tumor" & cell_type == "Hepatocyte"
#   expected n = 15,391
#
# Locked method:
#   OXPHOS AUCell scores are computed from 39 core ETC/OXPHOS
#   subunit-encoding genes using the same AUCell ranking framework.
#
# Locked manuscript checkpoints:
#   Glycolysis-OXPHOS Spearman rho approximately 0.066
#   Glycolysis-OXPHOS p approximately 2.44e-12
#
# Mandatory output order:
#   1. Source CSV files
#   2. QC CSV file
#   3. No PDF/PNG figures are generated by design
#
# Optional output:
#   results/FigS21_metabolic_specificity/seurat_final_tumor_hepatocyte_OXPHOS_AUC_metadata.csv
#
# This script does not use local absolute paths.
# ============================================================

options(stringsAsFactors = FALSE)

# Load the authoritative Figure 2C rank-balanced group helper.
helper_candidates <- c(
  file.path("scripts", "utils", "locked_fig2c_groups.R"),
  file.path("utils", "locked_fig2c_groups.R")
)
helper_path <- helper_candidates[file.exists(helper_candidates)][1]
if (length(helper_path) == 0 || is.na(helper_path)) {
  stop("Cannot find scripts/utils/locked_fig2c_groups.R. Run from the repository root.", call. = FALSE)
}
source(helper_path)


# ----------------------------
# Package handling
# ----------------------------
required_packages <- c(
  "Seurat",
  "SeuratObject",
  "AUCell",
  "dplyr",
  "tidyr",
  "readr",
  "tibble",
  "stringr"
)

load_or_stop <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop(
      "Package '", pkg, "' is required but not installed.\n",
      "Install CRAN packages with install.packages().\n",
      "Install Bioconductor packages with BiocManager::install().",
      call. = FALSE
    )
  }
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}

invisible(lapply(required_packages, load_or_stop))

# Avoid masking in interactive sessions.
select       <- dplyr::select
mutate       <- dplyr::mutate
filter       <- dplyr::filter
arrange      <- dplyr::arrange
summarise    <- dplyr::summarise
group_by     <- dplyr::group_by
ungroup      <- dplyr::ungroup
left_join    <- dplyr::left_join
rename       <- dplyr::rename
count        <- dplyr::count
bind_rows    <- dplyr::bind_rows
n_distinct   <- dplyr::n_distinct
all_of       <- dplyr::all_of

# ----------------------------
# User paths
# ----------------------------
# Recommended:
#   Place seurat_final.rds in the working directory.
# Optional:
#   Sys.setenv(SEURAT_FINAL_RDS = "/path/to/seurat_final.rds")
rds_path <- Sys.getenv("SEURAT_FINAL_RDS", unset = "seurat_final.rds")

outdir <- file.path("results", "FigS21_metabolic_specificity")
dir.create(outdir, showWarnings = FALSE, recursive = TRUE)

# ----------------------------
# Locked columns and expected values
# ----------------------------
patient_col  <- "patient"
celltype_col <- "cell_type"
site_col     <- "site"
gly_col      <- "Glycolysis_AUC"

expected_n_tumor_hep <- 15391L
expected_median_cut <- LOCKED_FIG2C_MEDIAN_AUC
expected_low_n <- 7696L
expected_high_n <- 7695L

expected_oxphos_gene_total <- 39L
expected_gly_ox_rho <- 0.066
rho_tolerance <- 0.030
median_tolerance <- 1e-6

# ----------------------------
# Gene sets
# ----------------------------
oxphos_genes_locked <- c(
  # Complex I
  "NDUFB3", "NDUFB4", "NDUFB5", "NDUFB6", "NDUFB7",
  "NDUFB8", "NDUFB9", "NDUFB10", "NDUFA1", "NDUFA2",
  "NDUFA3", "NDUFA4", "NDUFS1", "NDUFS2", "NDUFS3",
  # Complex II
  "SDHA", "SDHB", "SDHC", "SDHD",
  # Complex III
  "UQCRB", "UQCRC1", "UQCRC2", "UQCRQ", "CYC1",
  # Complex IV
  "COX4I1", "COX5A", "COX5B", "COX6A1", "COX6B1",
  "COX7A2", "COX8A",
  # Complex V
  "ATP5F1A", "ATP5F1B", "ATP5F1C", "ATP5F1D", "ATP5F1E",
  "ATP5MC1", "ATP5MC2", "ATP5MC3", "ATP5PB"
)

# Included only for manifest consistency and optional cross-checking.
glycolysis_genes_locked <- c(
  "HK1", "HK2", "GPI", "PFKL", "PFKP", "PFKM",
  "ALDOA", "ALDOB", "ALDOC", "TPI1", "GAPDH",
  "PGK1", "PGAM1", "ENO1", "ENO2", "PKM",
  "LDHA", "LDHB", "SLC2A1", "SLC2A3", "PFKFB3", "GCK"
)

ligands <- c("SPP1", "MIF")

# ----------------------------
# Helper functions
# ----------------------------
qc_row <- function(check, observed, expected, pass, tolerance = NA_character_) {
  tibble::tibble(
    check = check,
    observed = as.character(observed),
    expected = as.character(expected),
    tolerance = as.character(tolerance),
    pass = as.logical(pass)
  )
}

get_counts_mat <- function(seu, assay) {
  tryCatch(
    {
      SeuratObject::LayerData(seu, assay = assay, layer = "counts")
    },
    error = function(e) {
      Seurat::GetAssayData(seu, assay = assay, slot = "counts")
    }
  )
}

get_norm_mat <- function(seu, assay) {
  tryCatch(
    {
      SeuratObject::LayerData(seu, assay = assay, layer = "data")
    },
    error = function(e) {
      Seurat::GetAssayData(seu, assay = assay, slot = "data")
    }
  )
}

format_p <- function(x) {
  ifelse(is.na(x), NA_character_,
         ifelse(x == 0, "<1e-300", sprintf("%.3e", x)))
}

# ----------------------------
# Load object and validate metadata
# ----------------------------
if (!file.exists(rds_path)) {
  stop(
    "Cannot find seurat_final.rds.\n",
    "Current rds_path = ", rds_path, "\n",
    "Place seurat_final.rds in the working directory or set SEURAT_FINAL_RDS.",
    call. = FALSE
  )
}

seu <- readRDS(rds_path)
meta <- seu@meta.data %>% tibble::rownames_to_column("cell")

required_cols <- c(patient_col, celltype_col, site_col, gly_col)
missing_cols <- setdiff(required_cols, colnames(meta))
if (length(missing_cols) > 0) {
  stop("Missing required metadata columns: ", paste(missing_cols, collapse = ", "), call. = FALSE)
}

assay_use <- if ("RNA" %in% names(seu@assays)) "RNA" else DefaultAssay(seu)
counts_mat <- get_counts_mat(seu, assay_use)
norm_mat <- get_norm_mat(seu, assay_use)

# ----------------------------
# Select tumor-derived hepatocytes
# ----------------------------
tumor_hep <- meta %>%
  dplyr::filter(
    .data[[site_col]] == "Tumor",
    .data[[celltype_col]] == "Hepatocyte"
  ) %>%
  dplyr::mutate(
    patient = .data[[patient_col]],
    Glycolysis_AUC = as.numeric(.data[[gly_col]])
  )

cat("Selected tumor-derived hepatocytes:", nrow(tumor_hep), "\n")

if (nrow(tumor_hep) != expected_n_tumor_hep) {
  cat("\nAvailable Tumor-site cell_type labels:\n")
  print(sort(table(meta[[celltype_col]][meta[[site_col]] == "Tumor"]), decreasing = TRUE))
  stop(
    "Selected tumor-derived hepatocytes != 15,391. ",
    "Do not continue until metadata labels and selection rules are corrected.",
    call. = FALSE
  )
}

if (anyNA(tumor_hep$Glycolysis_AUC)) {
  stop("Glycolysis_AUC contains NA values in selected tumor-derived hepatocytes.", call. = FALSE)
}

# Locked rank-balanced Figure 2C assignment.
median_cut <- LOCKED_FIG2C_MEDIAN_AUC
tumor_hep <- tumor_hep %>%
  dplyr::mutate(
    gly_group = map_locked_fig2c_groups(cell, high_label = "High", low_label = "Low"),
    gly_group = factor(gly_group, levels = c("Low", "High"))
  )
if (anyNA(tumor_hep$gly_group)) stop("Locked Figure 2C grouping could not be mapped to every tumor-derived hepatocyte.", call. = FALSE)

gly_table <- table(tumor_hep$gly_group)
low_n <- as.integer(gly_table[["Low"]])
high_n <- as.integer(gly_table[["High"]])

cat("Median Glycolysis_AUC cutoff:", median_cut, "\n")
cat("GlycoLow:", low_n, " | GlycoHigh:", high_n, "\n")

# ----------------------------
# Gene availability checks
# ----------------------------
oxphos_present <- intersect(oxphos_genes_locked, rownames(counts_mat))
oxphos_missing <- setdiff(oxphos_genes_locked, oxphos_present)

glycolysis_present <- intersect(glycolysis_genes_locked, rownames(counts_mat))
glycolysis_missing <- setdiff(glycolysis_genes_locked, glycolysis_present)

ligands_present_norm <- intersect(ligands, rownames(norm_mat))
ligands_missing_norm <- setdiff(ligands, ligands_present_norm)

if (length(oxphos_present) < 4) {
  stop("Fewer than 4 OXPHOS genes are present; AUCell scoring is not meaningful.", call. = FALSE)
}

if (length(ligands_missing_norm) > 0) {
  stop("Missing ligand genes in normalized expression matrix: ",
       paste(ligands_missing_norm, collapse = ", "), call. = FALSE)
}

gene_set_source <- tibble::tibble(
  gene = c(oxphos_genes_locked, glycolysis_genes_locked),
  gene_set = c(
    rep("OXPHOS_39_core_ETC_subunits", length(oxphos_genes_locked)),
    rep("Glycolysis_22_locked_reference", length(glycolysis_genes_locked))
  ),
  present_in_counts_matrix = c(
    oxphos_genes_locked %in% rownames(counts_mat),
    glycolysis_genes_locked %in% rownames(counts_mat)
  )
)

# ----------------------------
# Compute OXPHOS AUCell in selected tumor hepatocytes
# ----------------------------
cells_use <- tumor_hep$cell
cells_missing <- setdiff(cells_use, colnames(counts_mat))
if (length(cells_missing) > 0) {
  stop("Some selected cells are missing from the counts matrix.", call. = FALSE)
}

cat("Building AUCell rankings for selected tumor-derived hepatocytes...\n")
expr_counts <- counts_mat[, cells_use, drop = FALSE]

rankings <- AUCell::AUCell_buildRankings(
  exprMat = expr_counts,
  plotStats = FALSE,
  verbose = FALSE
)

auc_max_rank <- ceiling(0.05 * nrow(expr_counts))

cat("Computing OXPHOS AUCell score with aucMaxRank = ", auc_max_rank, "...\n", sep = "")

cells_auc <- AUCell::AUCell_calcAUC(
  geneSets = list(OXPHOS = oxphos_present),
  rankings = rankings,
  aucMaxRank = auc_max_rank,
  verbose = FALSE
)

oxphos_auc <- as.numeric(AUCell::getAUC(cells_auc)["OXPHOS", ])
names(oxphos_auc) <- colnames(AUCell::getAUC(cells_auc))

# Align back to tumor_hep order.
tumor_hep <- tumor_hep %>%
  dplyr::mutate(
    OXPHOS_AUC = as.numeric(oxphos_auc[cell])
  )

if (anyNA(tumor_hep$OXPHOS_AUC)) {
  stop("Computed OXPHOS_AUC contains NA values after alignment.", call. = FALSE)
}

# ----------------------------
# Extract ligand expression and compute cross-checks
# ----------------------------
expr_ligand <- as.matrix(norm_mat[ligands, tumor_hep$cell, drop = FALSE])

cell_source <- tumor_hep %>%
  dplyr::select(
    cell,
    patient,
    Glycolysis_AUC,
    OXPHOS_AUC,
    gly_group
  ) %>%
  dplyr::mutate(
    SPP1_log_normalized = as.numeric(expr_ligand["SPP1", cell]),
    MIF_log_normalized = as.numeric(expr_ligand["MIF", cell])
  )

cor_go <- suppressWarnings(
  stats::cor.test(
    cell_source$Glycolysis_AUC,
    cell_source$OXPHOS_AUC,
    method = "spearman",
    exact = FALSE
  )
)

gly_ox_rho <- as.numeric(cor_go$estimate)
gly_ox_p <- as.numeric(cor_go$p.value)

summary_source <- cell_source %>%
  dplyr::summarise(
    n_cells = dplyr::n(),
    n_patients = dplyr::n_distinct(patient),
    glycolysis_auc_min = min(Glycolysis_AUC),
    glycolysis_auc_median = median(Glycolysis_AUC),
    glycolysis_auc_max = max(Glycolysis_AUC),
    oxphos_auc_min = min(OXPHOS_AUC),
    oxphos_auc_median = median(OXPHOS_AUC),
    oxphos_auc_max = max(OXPHOS_AUC),
    gly_ox_spearman_rho = gly_ox_rho,
    gly_ox_spearman_p = gly_ox_p
  )

patient_summary <- cell_source %>%
  dplyr::group_by(patient) %>%
  dplyr::summarise(
    n_cells = dplyr::n(),
    mean_glycolysis_auc = mean(Glycolysis_AUC),
    median_glycolysis_auc = median(Glycolysis_AUC),
    mean_oxphos_auc = mean(OXPHOS_AUC),
    median_oxphos_auc = median(OXPHOS_AUC),
    mean_SPP1_log_normalized = mean(SPP1_log_normalized),
    mean_MIF_log_normalized = mean(MIF_log_normalized),
    .groups = "drop"
  ) %>%
  dplyr::arrange(patient)

manifest <- tibble::tibble(
  item = c(
    "script",
    "role",
    "figure_mapping",
    "input_object",
    "assay_used",
    "counts_layer",
    "normalized_layer",
    "selection_rule",
    "selected_tumor_hepatocytes",
    "glycolysis_variable",
    "OXPHOS_gene_set",
    "OXPHOS_genes_present",
    "OXPHOS_genes_missing",
    "AUCell_aucMaxRank",
    "downstream_plot_script",
    "plot_title_policy"
  ),
  value = c(
    "14_OXPHOS_metabolic_specificity.R",
    "Compute OXPHOS_AUC source data and QC for S21 metabolic-specificity analysis",
    "No figure is generated here. Supplementary Figure S21 is generated by 17_partial_correlation_metabolic_specificity.R. Supplementary Figure S22 is NicheNet, not OXPHOS.",
    rds_path,
    assay_use,
    "counts",
    "data / log-normalized expression",
    "site == 'Tumor' & cell_type == 'Hepatocyte'",
    as.character(nrow(tumor_hep)),
    "Glycolysis_AUC",
    "39 core ETC/OXPHOS subunit-encoding genes",
    paste(oxphos_present, collapse = ";"),
    ifelse(length(oxphos_missing) == 0, "None", paste(oxphos_missing, collapse = ";")),
    as.character(auc_max_rank),
    "17_partial_correlation_metabolic_specificity.R",
    "No PDF/PNG figure generated by this script"
  )
)

# ----------------------------
# Write source CSVs before QC
# ----------------------------
cell_source_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_cell_source.csv")
summary_source_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_summary_source.csv")
patient_summary_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_patient_summary_source.csv")
gene_set_csv <- file.path(outdir, "FigS21_OXPHOS_gene_set_source.csv")
manifest_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_manifest.csv")

readr::write_csv(cell_source, cell_source_csv)
readr::write_csv(summary_source, summary_source_csv)
readr::write_csv(patient_summary, patient_summary_csv)
readr::write_csv(gene_set_source, gene_set_csv)
readr::write_csv(manifest, manifest_csv)

cat("\nSource CSVs written:\n")
cat("  ", cell_source_csv, "\n", sep = "")
cat("  ", summary_source_csv, "\n", sep = "")
cat("  ", patient_summary_csv, "\n", sep = "")
cat("  ", gene_set_csv, "\n", sep = "")
cat("  ", manifest_csv, "\n", sep = "")

# ----------------------------
# Mandatory QC
# ----------------------------
qc <- dplyr::bind_rows(
  qc_row(
    "Input object exists",
    file.exists(rds_path),
    TRUE,
    file.exists(rds_path)
  ),
  qc_row(
    "Required metadata columns",
    paste(required_cols, collapse = ";"),
    paste(required_cols, collapse = ";"),
    length(missing_cols) == 0
  ),
  qc_row(
    "Selected tumor-derived hepatocytes",
    nrow(tumor_hep),
    expected_n_tumor_hep,
    nrow(tumor_hep) == expected_n_tumor_hep
  ),
  qc_row(
    "Median Glycolysis_AUC cutoff",
    sprintf("%.7f", median_cut),
    sprintf("%.7f", expected_median_cut),
    abs(median_cut - expected_median_cut) <= median_tolerance,
    median_tolerance
  ),
  qc_row(
    "GlycoLow count",
    low_n,
    expected_low_n,
    low_n == expected_low_n
  ),
  qc_row(
    "GlycoHigh count",
    high_n,
    expected_high_n,
    high_n == expected_high_n
  ),
  qc_row(
    "OXPHOS locked gene count",
    length(oxphos_genes_locked),
    expected_oxphos_gene_total,
    length(oxphos_genes_locked) == expected_oxphos_gene_total
  ),
  qc_row(
    "OXPHOS genes present in counts matrix",
    length(oxphos_present),
    "Prefer 39/39; all missing genes are reported if not",
    length(oxphos_present) >= 30
  ),
  qc_row(
    "Ligands present in normalized matrix",
    paste(ligands_present_norm, collapse = ";"),
    "SPP1;MIF",
    length(ligands_missing_norm) == 0
  ),
  qc_row(
    "OXPHOS_AUC finite values",
    all(is.finite(cell_source$OXPHOS_AUC)),
    TRUE,
    all(is.finite(cell_source$OXPHOS_AUC))
  ),
  qc_row(
    "Glycolysis-OXPHOS Spearman rho",
    sprintf("%.6f", gly_ox_rho),
    sprintf("%.3f", expected_gly_ox_rho),
    abs(gly_ox_rho - expected_gly_ox_rho) <= rho_tolerance,
    rho_tolerance
  ),
  qc_row(
    "Glycolysis-OXPHOS Spearman p",
    format_p(gly_ox_p),
    "approximately 2.44e-12; exact value can vary slightly with AUCell/ranking implementation",
    is.finite(gly_ox_p) && gly_ox_p < 1e-6
  ),
  qc_row(
    "Figure mapping corrected",
    "No S22 output generated by 14",
    "S21 input/QC only; S22 belongs to NicheNet",
    TRUE
  ),
  qc_row(
    "No PDF/PNG generated by design",
    "TRUE",
    "TRUE",
    TRUE
  )
)

qc_status <- ifelse(all(qc$pass), "PASS", "FAIL")
qc <- qc %>% dplyr::mutate(overall_qc = qc_status)

qc_csv <- file.path(outdir, "FigS21_OXPHOS_AUC_QC_check.csv")
readr::write_csv(qc, qc_csv)

cat("\nQC CSV written:\n")
cat("  ", qc_csv, "\n", sep = "")
cat("\nQC table:\n")
print(qc)

if (!all(qc$pass)) {
  stop(
    "Mandatory QC failed. Source CSV and QC CSV were written. No figures were generated by design.\n",
    "Inspect: ", qc_csv,
    call. = FALSE
  )
}

cat("\nQC PASS. No manuscript figure was generated by this script.\n")
cat("Use 17_partial_correlation_metabolic_specificity.R for Supplementary Figure S21 plotting.\n")
cat("14_OXPHOS_metabolic_specificity.R completed successfully.\n")
